[library]
namespace = "Pango"
version = "1.0"
browse_url = "https://gitlab.gnome.org/GNOME/pango/"
repository_url = "https://gitlab.gnome.org/GNOME/pango.git"
website_url = "https://www.pango.org"
authors = "Owen Taylor, Behdad Esfahbod"
logo_url = "https://pango.gnome.org/ScriptGallery?action=AttachFile&do=get&target=pango-name.png"
license = "GPL-2.1-or-later"
description = "Internationalized text layout and rendering"
dependencies = [ "GObject-2.0", "HarfBuzz-0.0", "cairo-1.0" ]

  [dependencies."GObject-2.0"]
  name = "GObject"
  description = "The base type system library"
  docs_url = "https://developer.gnome.org/gobject/stable"

  [dependencies."HarfBuzz-0.0"]
  name = "HarfBuzz"
  description = "A text shaping library"
  docs_url = "https://harfbuzz.github.io/"

  [dependencies."cairo-1.0"]
  name = "cairo"
  description = "A vector graphics library"
  docs_url = "https://www.cairographics.org/manual/"

[theme]
name = "basic"

[source-location]
base_url = "https://gitlab.gnome.org/GNOME/pango/-/blob/master/"

[extra]
content_files = [
  [ "pango_markup.md", "Pango Markup" ],
  [ "pango_rendering.md", "Pango Rendering" ],
]
